#!/bin/bash

source sources/episode.sh

function programme() {
  local episodes="$1"
  local soustitres="$2"

  local episode
  for episode in $(find "${episodes}" -name "*.*"); do
    _copie_le_soustitre_qui_correspond
  done
}

function _copie_le_soustitre_qui_correspond() {
  local soustitre
  for soustitre in $(find "${soustitres}" -name "*.*"); do
    _si_le_soustitre_correspond_copie_le
  done
}

function _si_le_soustitre_correspond_copie_le() {
  if episode__correspondent "${soustitre}" "${episode}"; then
    cp "${soustitre}" "$(episode__soustitre_final "${episode}")"
  fi
}

programme "$@"